# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='guest',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
